### ISSUE TITLE
"requires cl_khr_fp64 extension to be enabled"

### ISSUE THREAD

**Issue by Dekken** [RadeonOpenCompute/ROCm-Device-Libs#10]
[gist](https://gist.githubusercontent.com/Dekken/8a486d1f382b63ca9e0c93cea5d62e1a/raw/9d4e4fb6dee19e436efc1ce4b7b573e6bc1b5dd2/devlibs.28_12_2016.error)

**Comment by nhaustov** [comment]
The files are compiled with -cl-std=CL2.0 and explicitly enabling cl_khr_fp64 extension should not be necessary. Some recent change in clang must have broken this.

**Comment by adityaatluri** [comment]
Hi @nhaustov ,
I am able to reproduce the error.

**Comment by kzhuravl** [comment]
I will merge a fix in a bit.

**Comment by kzhuravl** [comment]
Hi @Dekken and @adityaatluri,

Can you rebuild clang with this merge included:
https://github.com/RadeonOpenCompute/clang/pull/26

And try to build device libs again?

Thanks,
Konstantin

**Comment by adityaatluri** [comment]
Hi @kzhuravl ,
Works fine. Building HCC 4.0 now, will let you know if anything breaks there (components from rocdl).

**Comment by Dekken** [comment]
Fixed on my end too
