### ISSUE TITLE
Create a timer in GPU kernels with LLVM instruction "__llvm_amdgcn_s_memrealtime"?

### ISSUE THREAD

**Issue by zjing14** [RadeonOpenCompute/ROCm-Device-Libs#45]
Hi,

I found LLVM instruction: __llvm_amdgcn_s_memrealtime in "irif/inc/irif.h". It seems that the instruction has been used in __clock_u64() in hc_amdgcn.ll. I am wondering what clock frequency is （i.e., CLOCKS_PER_SEC), so we can create a timer in GPU kernels.

Thanks,

Jing

**Comment by b-sumner** [comment]
You can use the HSA_SYSTEM_INFO_TIMESTAMP_FREQUENCY query for this.

Note that you cannot expect that instructions will not be moved across calls to this intrinsic so you cannot reliably "time" a set of operations.

**Comment by b-sumner** [comment]
I'm assuming this was answered satisfactorily.  Please reopen if I'm mistaken.
