### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by lotus33** [RadeonOpenCompute/ROCm-Device-Libs#5]
Cloning into 'llvm_amd-common'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Thanks

**Comment by gstoner** [comment]
This looks like a GitHub issue.

**Comment by Dekken** [comment]
The guide assumes you're environment has ssh keys associated with github, just use

git clone https://github.com/RadeonOpenCompute/ROCm-Device-Libs

**Comment by gstoner** [comment]
No.  you only need that library if you building the HCC compiler from Source.   This is not used by the base ROCm library only in the LLVM compiler for HCC and soon OpenCL.


On Oct 29, 2016, at 7:44 AM, ♦♣♠♥ <notifications@github.com<mailto:notifications@github.com>> wrote:


The guide assumes you're environment has ssh keys associated with github, just use

git clone https://github.com/RadeonOpenCompute/ROCm-Device-Libs

**Comment by b-sumner** [comment]
I'm assuming this can be closed at this point.  Please reopen if I'm mistaken.
