### ISSUE TITLE
y1(-0.0) returns +inf (instead of -inf or Nan)

### ISSUE THREAD

**Issue by VinInn** [RadeonOpenCompute/ROCm-Device-Libs#70]
I noticed that both y1f and y1 return +inf for -0.0 (and NaN for any other negative number)
y0(-0.0) return -inf 

linux libm return -inf for any negative number (NaN is most probably more correct)
+inf is definitively wrong.

I am using rocm 4.2 out of the box

**Comment by b-sumner** [comment]
Thanks, we'll take a look.

**Comment by b-sumner** [comment]
This will be fixed in a future release.  Thanks again for bringing it to our attention.

**Comment by VinInn** [comment]
Thanks for the fast action.
I am checking OCML against MPFR and results are very encouraging.
Sorry to highjack this thread: is OCML supported on platforms other than Radeon (say x86-64)?

**Comment by b-sumner** [comment]
OCML is specifically for use by code running on AMD GPUs.

**Comment by b-sumner** [comment]
This has been fixed.
