### ISSUE TITLE
tgammaf becomes inf for tiny values of its argument

### ISSUE THREAD

**Issue by VinInn** [RadeonOpenCompute/ROCm-Device-Libs#74]
tgammaf returns inf for |x|<= 0x1.fffffcp-127.  This is the largest float for which x*x=0;
Other libraries return  a value equal to 1/x  (8.50706e+37)

**Comment by b-sumner** [comment]
Thanks, we'll take a look.

**Comment by b-sumner** [comment]
This has been fixed.
