### ISSUE TITLE
recent improvements in ocml NOT in release 4.5

### ISSUE THREAD

**Issue by VinInn** [RadeonOpenCompute/ROCm-Device-Libs#77]
From my tests I think that the recent improvements in ocml are not included in release 4.5.
Am I missing anything?

Is the improved ocml foreseen to be included soon in a future release?

**Comment by b-sumner** [comment]
The improvements will eventually show up.  ROCm releases can get pretty far behind the tip due to the time it takes to do all the release testing, etc.

**Comment by VinInn** [comment]
All improvements seem to be in 5.0.0.
We have updated our paper https://gitlab.inria.fr/zimmerma/math_accuracy/-/blob/master/latex/glibc235.tex

**Comment by b-sumner** [comment]
Improvements have appeared in released ROCm versions starting with 5.0.
