### ISSUE TITLE
amdgcn/bitcodes relocation for distributions

### ISSUE THREAD

**Issue by emollier** [RadeonOpenCompute/ROCm-Device-Libs#79]
Greetings,

While attempting to package _rocm-device-libs_ for the debian project, I noticed _amdgcn/bitcodes_ landed straight into _$PREFIX/amdgcn_.  From an operating system perspective, since this is causing installation below _/usr/amdgcn_ which is not conformant to FHS, I had to shift the directory a bit by applying [this patch on Salsa](https://salsa.debian.org/rocm-team/rocm-device-libs/-/blob/debian/4.5.2-1_exp1/debian/patches/cmake-amdgcn-bitcode.patch) to move to _/usr/share/amdgcn_.

Would such change be of interest on your side?  Do you foresee any issue if bitcodes are moved around this way, and if so have a more appropriate approach to suggest?  I'm afraid my patching could be rather naive at the moment.

Thank you for making ROCm freely available!

Have a nice day,  :)\
Étienne.

PS: my rationale for using _/usr/share_ is that the produced bitcodes turn out to be CPU architecture independent data, but I'm also fine with _/usr/lib/amdgcn_ (as long as it is not _/usr/lib/$TRIPLET/amdgcn_, the _$TRIPLET_ would force us to make a set of architecture dependent packages instead of one _all_ package, so not ideal from my point of view).

**Comment by b-sumner** [comment]
Hello @emollier, and thanks for bringing this up.  We are aiming to change the location of these libraries and have included external discussion.  These libraries properly belong in the LLVM/clang resource directory and we will likely move them there.

**Comment by emollier** [comment]
Hi b-sumner,

Thank you for the clarification.  So this is a temporary
workaround and will see how things evolve in upcoming ROCm
versions.

Have a nice day,  :)
Étienne.

**Comment by Mystro256** [comment]
Hi @emollier,

I have been working with @t-tye, and an engineer is currently working on fixing the installation path as @b-sumner mentioned.
Once the patch has been pushed to amd-stg-open, I will try to remember to update this ticket, so you can cherry-pick it as a Debian quilt patch.

I spoke with the senior technical leads, and my impression is that this:

> the produced bitcodes turn out to be CPU architecture independent data

Is not strictly true and should not be assumed. For best results, you need to strongly tie the device-libs, llvm, and clang version together. The "LLVM/clang resource directory" that @b-sumner mentioned is likely `/usr/lib/llvm-13/lib/clang/13.0.1/lib/` in Debian, e.g. see the [libclang-common-13-dev package](https://packages.debian.org/sid/amd64/libclang-common-13-dev/filelist).

I would advise that you talk with the LLVM and Clang Debian maintainers, so you can co-ordinate with them effectively.

Thanks/Merci!

**Comment by emollier** [comment]
Hi Jeremy,

Thanks for considering sharing the patch!

Thanks also for the warning, I made the necessary adjustments so
the current quilt patch [1] points to an architecture dependent
location, and eventually allows for proper multiarchitecture
support; this is currently /usr/lib/$TRIPLET/amdgcn, but can be
adjusted more easily than the Architecture: all/any flag.

[1]: https://salsa.debian.org/rocm-team/rocm-device-libs/-/blob/b2523c745803a4ada3dc75134e9e82d4172b574d/debian/patches/cmake-amdgcn-bitcode.patch

Debian LLVM Maintainers are also pinged for coordination if need
be [2].

[2]: https://lists.debian.org/debian-ai/2022/02/msg00008.html

Have a nice day,  :)
-- 
Étienne Mollier ***@***.***>
Fingerprint:  8f91 b227 c7d6 f2b1 948c  8236 793c f67e 8f0d 11da
Sent from /dev/pts/2, please excuse my verbosity.
On air: The Gift - Tuesday's Child
