### ISSUE TITLE
`__builtin_amdgcn_s_sendmsg_rtnl` - ockl/src/mtime.cl:20:12: error: use of undeclared identifier

### ISSUE THREAD

**Issue by SamuelMarks** [RadeonOpenCompute/ROCm-Device-Libs#91]
```c
ROCm/ROCm-Device-Libs/ockl/src/mtime.cl:20:12: error: use of undeclared identifier '__builtin_amdgcn_s_sendmsg_rtnl'
    return __builtin_amdgcn_s_sendmsg_rtnl(0x83);
           ^
1 error generated.
```

I am using ROCm-Device-Libs @ 4d86a313a33027cff82dc73fe9b8395a7a96eb04 and LLVM @ [`a29fe42`](https://github.com/RadeonOpenCompute/llvm-project/commit/a29fe425c7b0e5aba97ed2f95f61fd5ecba68aed).

`grep`ing around I found [`BuiltinsAMDGPU.def#L282`](https://github.com/RadeonOpenCompute/llvm-project/blob/a29fe42/clang/include/clang/Basic/BuiltinsAMDGPU.def#L282):
```c
TARGET_BUILTIN(__builtin_amdgcn_s_sendmsg_rtnl, "UWiUIi", "n", "gfx11-insts")
```

So not sure if an `include` is missing or a library isn't being linked?

**Comment by b-sumner** [comment]
@SamuelMarks the clang you are using is probably not as recent as the device library hash you are compiling.  I'd consider checking out an older hash of device library if you can't update your compiler.

**Comment by SamuelMarks** [comment]
I'm on the amd-stg-open branch of https://github.com/RadeonOpenCompute/llvm-project. Building @ [`fd2313`](https://github.com/RadeonOpenCompute/llvm-project/tree/fd231326). Will let you know if it succeeds with this version; once build finishes.

**Comment by b-sumner** [comment]
Thanks.  Any additional concerns?

**Comment by b-sumner** [comment]
@SamuelMarks looks like that other issue is in progress.  Are you OK to close this one?
