### ISSUE TITLE
Fails to build against llvm 16.0.4 with "Option 'debug-counter' registered more than once!"

### ISSUE THREAD

**Issue by Qwinci** [RadeonOpenCompute/ROCm-Device-Libs#94]
```
FAILED: lib/amdgcn/bitcode/oclc_daz_opt_off.bc /var/tmp/portage/dev-libs/rocm-device-libs-5.5.1/work/ROCm-Device-Libs-rocm-5.5.1_build/lib/amdgcn/bitcode/oclc_daz_opt_off.bc 
cd /var/tmp/portage/dev-libs/rocm-device-libs-5.5.1/work/ROCm-Device-Libs-rocm-5.5.1_build/oclc && /usr/lib/llvm/16/bin/llvm-link -o oclc_daz_opt_off.link0.lib.bc @oclc_daz_opt_off_response && /usr/lib/llvm/16/bin/llvm-link -internalize -only-needed oclc_daz_opt_off.link0.lib.bc -o oclc_daz_opt_off.lib.bc && /usr/lib/llvm/16/bin/opt -passes=amdgpu-unify-metadata,strip -o oclc_daz_opt_off.strip.bc oclc_daz_opt_off.lib.bc && /var/tmp/portage/dev-libs/rocm-device-libs-5.5.1/work/ROCm-Device-Libs-rocm-5.5.1_build/utils/prepare-builtins/prepare-builtins -o /var/tmp/portage/dev-libs/rocm-device-libs-5.5.1/work/ROCm-Device-Libs-rocm-5.5.1_build/lib/amdgcn/bitcode/oclc_daz_opt_off.bc oclc_daz_opt_off.strip.bc
: CommandLine Error: Option 'debug-counter' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```
there are more similar errors following, this is the whole build log.
[build.log](https://github.com/RadeonOpenCompute/ROCm-Device-Libs/files/11634173/build.log)

**Comment by DiabeticCrab** [comment]
Hello, fellow Gentoo user!
I figured it out - it's a problem with the distro patches supplied with the ebuilds. Edit the rocm-device-libs-5.5.1 ebuild to not include  "rocm-device-libs-5.1.3-llvm-link.patch" anymore and have it apply the patch in the attachment instead.
[rocm-device-libs-5.5.1-fix-llvm-link.patch](https://github.com/RadeonOpenCompute/ROCm-Device-Libs/files/11671180/rocm-device-libs-5.5.1-fix-llvm-link.patch.txt)

**Comment by Qwinci** [comment]
Thanks, that makes it work!

**Comment by Qwinci** [comment]
@DiabeticCrab I got rocm-comgr to compile with these patches
	"${FILESDIR}/${PN}-5.1.3-rocm-path.patch"
	"${FILESDIR}/0001-Specify-clang-exe-path-in-Driver-Creation.patch"
	"${FILESDIR}/0001-Find-CLANG_RESOURCE_DIR-using-clang-print-resource-d.patch"
	"${FILESDIR}/${PN}-5.3.3-HIPIncludePath-not-needed.patch"
	"${FILESDIR}/${PN}-5.5.1-fix-tests.patch"
	"${FILESDIR}/${PN}-5.3.3-fno-stack-protector.patch"
	"${FILESDIR}/${PN}-5.3.3-remove-h-option.patch"
	"${FILESDIR}/${PN}-5.5.1-nullopt.patch"
	"${FILESDIR}/${PN}-5.5.1-opt_mrelax.patch"
	"${FILESDIR}/${PN}-5.5.1-lld-include.patch"
	"${FILESDIR}/${PN}-5.5.1-subtargetfeatures.patch"

where most of the new ones are just direct patches created from commits in the upstream repo except for the fix-tests one.
[rocm-comgr-5.5.1-fix-tests.patch.txt](https://github.com/RadeonOpenCompute/ROCm-Device-Libs/files/11747523/rocm-comgr-5.5.1-fix-tests.patch.txt)
[rocm-comgr-5.5.1-lld-include.patch.txt](https://github.com/RadeonOpenCompute/ROCm-Device-Libs/files/11747524/rocm-comgr-5.5.1-lld-include.patch.txt)
[rocm-comgr-5.5.1-nullopt.patch.txt](https://github.com/RadeonOpenCompute/ROCm-Device-Libs/files/11747525/rocm-comgr-5.5.1-nullopt.patch.txt)
[rocm-comgr-5.5.1-opt_mrelax.patch.txt](https://github.com/RadeonOpenCompute/ROCm-Device-Libs/files/11747526/rocm-comgr-5.5.1-opt_mrelax.patch.txt)
[rocm-comgr-5.5.1-subtargetfeatures.patch.txt](https://github.com/RadeonOpenCompute/ROCm-Device-Libs/files/11747527/rocm-comgr-5.5.1-subtargetfeatures.patch.txt)

**Comment by Qwinci** [comment]
for rocminfo I used this upstream commit
[rocminfo-5.5.1-detect-builtin-amdgpu.patch.txt](https://github.com/RadeonOpenCompute/ROCm-Device-Libs/files/11747550/rocminfo-5.5.1-detect-builtin-amdgpu.patch.txt)

**Comment by Qwinci** [comment]
and for hip this patch along with ebuild modifications to not apply some of the other patches, since I am not sure what was done to the things they patch but atleast by a quick look I didn't the things they are patching in there anymore. Also atleast built with clang thinlto using this hip in Blender seems to cause Blender to just segfault, not sure why. 
[hip-5.5.1.ebuild.txt](https://github.com/RadeonOpenCompute/ROCm-Device-Libs/files/11747598/hip-5.5.1.ebuild.txt)
[hip-5.5.1-disable-Werror.patch.txt](https://github.com/RadeonOpenCompute/ROCm-Device-Libs/files/11747592/hip-5.5.1-disable-Werror.patch.txt)

**Comment by DiabeticCrab** [comment]
@Qwinci You're awesome! Works flawlessly for me. Many thanks!
