### ISSUE TITLE
New location of repo

### ISSUE THREAD

**Issue by powderluv** [RadeonOpenCompute/ROCm-Device-Libs#97]
With the deprecation notice it points to the monorepo but there is no amd/ directory there or in upstream LLVM. This is a welcome transition and we would like to use / build from the new location and remove this dependency.

**Comment by b-sumner** [comment]
Are you looking in https://github.com/RadeonOpenCompute/llvm-project ?  I see an amd directory at the top level.

**Comment by powderluv** [comment]
Perfect thanks you. We will switch to using this repo in our ROCM enablement in IREE https://github.com/openxla/iree/pull/14894 . BTW would this be going to the upstream monorepo in some form ?

Thanks

**Comment by kzhuravl** [comment]
Hi @powderluv, currently there are no plans to move device-libs into the upstream monorepo.

**Comment by powderluv** [comment]
Sounds good thank you.
